services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  mlflow:
    build:
      context: .
      dockerfile: mlflow.dockerfile
    ports:
      - "5001:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./mlartifacts:/mlartifacts:rw

  deploy_model:
    build:
      context: .
      dockerfile: deploy_model.dockerfile
    depends_on:
      - mlflow
    ports:
      - "5002:5002"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./mlartifacts:/mlartifacts:rw

  prefect-server:
    image: prefecthq/prefect:3-latest
    ports:
      - "4200:4200"
    environment:
      - PREFECT_UI_URL=http://127.0.0.1:4200/api
      - PREFECT_API_URL=http://127.0.0.1:4200/api
    command: prefect server start --host 0.0.0.0
    volumes:
      - ./prefect:/app/prefect:ro
      - ./data:/app/data:rw
      - ./scripts:/app/scripts:ro

  prefect-worker:
    build:
      context: .
      dockerfile: prefect-worker.dockerfile
    depends_on:
      - prefect-server
      - deploy_model
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MODEL_SERVICE_URL=http://deploy_model:5002  # Add this line
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT:-mlops-zoomcamp-1337420697}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/bigquery-credentials.json
    volumes:
      - ./prefect:/app/prefect:ro
      - ./data:/app/data:rw
      - ./monitoring:/app/monitoring:rw
      - ./scripts:/app/scripts:ro
      - ./bigquery-credentials.json:/app/bigquery-credentials.json:ro
      - ./.env:/app/.env:ro
      - ./mlartifacts:/app/mlartifacts:ro
    working_dir: /app
    command: python prefect/deploy.py