channels:
- conda-forge
dependencies:
- python=3.12.11
- pip
- pip:
  - mlflow==3.2.0
  - numpy==1.26.4
  - pandas==2.3.1
  - psutil==7.0.0
  - pyarrow==15.0.2
  - scikit-learn==1.7.1
  - scipy==1.16.1
  - xgboost==3.0.4
name: mlflow-env
